    <!-- HTML5_HEAD_TITLE_START -->
    <title><?php echo PROJECT_NAME." :: ".MODULE_NAME; ?></title>
    <!-- HTML5_HEAD_TITLE_END -->

    <!-- HTML5_HEAD_META_START -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <meta name="Author" content="ISC. Jonathan S&#225;nchez Luna" />
	<meta name="generator" content="IP20 WDB: IP20's Web Development Bot" />
	<meta name="keywords" content="IP20, Ingeniería, Productos, Tecnologías de la Información, Tijuana, Baja California, M&#233;xico, JJ-POS, Point Of Sale, Poyong, Pollos, ISC. Jonathan S&#225;nchez Luna, Jennifer Andrea Largo Castro" />
	<meta name="description" content="UNITICKETS: Uniradio's Ticket Platform" />
    <!-- HTML5_HEAD_META_END -->

    <!-- HTML5_HEAD_LINK_START -->
	<link rel="shortcut icon" href="<?php echo BASE_DIR; ?>siunitickets.png" type="image/x-icon" />
	<link rel="icon" href="<?php echo BASE_DIR; ?>iunitickets.png" type="image/ico" />
	<link rel="stylesheet" media="all" type="text/css" href="<?php echo BASE_DIR; ?>frontend/styles/main.css" />
    <!-- HTML5_HEAD_LINK_END -->

    <!-- HTML5_HEAD_SCRIPT_START -->
    <script type="text/javascript" src="<?php echo BASE_DIR; ?>frontend/scripts/config.js"></script>
    <script type="text/javascript" src="<?php echo BASE_DIR; ?>frontend/scripts/main.js"></script>
    <script type="text/javascript" src="<?php echo BASE_DIR; ?>frontend/scripts/Authorization.js"></script>
    <script type="text/javascript">const MODULE_NAME = '<?php echo MODULE_NAME; ?>';</script>
    <!-- HTML5_HEAD_SCRIPT_END -->